### ICU Mortality and Risk Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("icu_mortality.csv")
df.head()

,patient_id,age,gender,admission_type,comorbidity_score,heart_rate_mean,heart_rate_std,heart_rate_max,heart_rate_min,systolic_bp_mean,...,glucose_mean,lactate_mean,urine_output_total,ventilation_required,vasopressor_used,length_of_stay_days,apache_score,sofa_score,sepsis_flag,mortality_label
0,PAT000001,32,Male,Urgent,3.75,136.06,19.64,162.01,127.16,104.04,...,73.71,7.77,4245.99,0,0,6.32,15.65,10.50,0,0
1,PAT000002,46,Male,Urgent,2.91,108.95,7.79,124.18,94.79,131.05,...,78.36,5.06,1267.36,0,1,29.00,33.29,6.09,0,1
2,PAT000003,87,Male,Urgent,6.84,95.21,7.44,117.54,89.35,171.84,...,168.41,1.89,4863.13,1,1,26.95,25.93,18.44,0,1
3,PAT000004,21,Male,Emergency,1.96,63.62,11.51,82.22,51.84,164.59,...,214.40,1.06,4940.99,1,0,1.16,33.54,14.14,0,1
4,PAT000005,21,Male,Urgent,7.71,65.92,12.17,74.98,39.34,146.10,...,201.33,5.28,4492.46,0,0,21.68,31.63,11.23,0,0

In [3]:
df.shape

(15000, 24)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   patient_id             15000 non-null  object
 1   age                    15000 non-null  int64
 2   gender                 15000 non-null  object
 3   admission_type         15000 non-null  object
 4   comorbidity_score      15000 non-null  float64
 5   heart_rate_mean        15000 non-null  float64
 6   heart_rate_std         15000 non-null  float64
 7   heart_rate_max         15000 non-null  float64
 8   heart_rate_min         15000 non-null  float64
 9   systolic_bp_mean       15000 non-null  float64
 10  systolic_bp_std        15000 non-null  float64
 11  respiratory_rate_mean  15000 non-null  float64
 12  spo2_mean              15000 non-null  float64
 13  temperature_mean       15000 non-null  float64
 14  glucose_mean           15000 non-null  float64
 15  lactate_mean           15000 non-null  float64
 16  urine_output_total     15000 non-null  float64
 17  ventilation_required   15000 non-null  int64
 18  vasopressor_used       15000 non-null  int64
 19  length_of_stay_days    15000 non-null  float64
 20  apache_score           15000 non-null  float64
 21  sofa_score             15000 non-null  float64
 22  sepsis_flag            15000 non-null  int64
 23  mortality_label        15000 non-null  int64
dtypes: float64(16), int64(5), object(3)
memory usage: 2.7+ MB

In [5]:
df.describe()

,age,comorbidity_score,heart_rate_mean,heart_rate_std,heart_rate_max,heart_rate_min,systolic_bp_mean,systolic_bp_std,respiratory_rate_mean,spo2_mean,...,glucose_mean,lactate_mean,urine_output_total,ventilation_required,vasopressor_used,length_of_stay_days,apache_score,sofa_score,sepsis_flag,mortality_label
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,...,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,53.987533,4.988851,100.026900,15.087800,122.477551,82.523059,134.780335,12.539299,23.612935,90.051769,...,159.115675,4.270719,2760.416425,0.302200,0.245133,15.432166,22.496783,9.982515,0.201933,0.227867
std,21.027881,2.896171,23.187937,5.780114,25.304740,24.393954,25.982344,4.327404,6.654296,5.750619,...,51.867736,2.154312,1297.457979,0.459227,0.430181,8.368326,10.087201,5.747374,0.401456,0.419470
min,18.000000,0.000000,60.000000,5.000000,65.260000,30.600000,90.010000,5.000000,12.000000,80.000000,...,70.010000,0.500000,500.030000,0.000000,0.000000,1.000000,5.000000,0.000000,0.000000,0.000000
25%,36.000000,2.420000,80.027500,10.077500,102.430000,62.207500,112.187500,8.780000,17.880000,85.080000,...,114.430000,2.420000,1636.355000,0.000000,0.000000,8.140000,13.640000,4.967500,0.000000,0.000000
50%,54.000000,4.980000,99.925000,15.180000,122.450000,82.575000,134.555000,12.570000,23.650000,90.020000,...,158.615000,4.290000,2767.555000,0.000000,0.000000,15.470000,22.635000,10.040000,0.000000,0.000000
75%,72.000000,7.540000,120.160000,20.080000,142.465000,102.842500,157.370000,16.260000,29.400000,95.000000,...,203.870000,6.120000,3887.780000,1.000000,0.000000,22.670000,31.140000,14.930000,0.000000,0.000000
max,90.000000,10.000000,140.000000,25.000000,179.320000,134.330000,180.000000,20.000000,35.000000,100.000000,...,249.980000,8.000000,4999.540000,1.000000,1.000000,30.000000,40.000000,20.000000,1.000000,1.000000

In [6]:
df.isnull().sum().sort_values(ascending=False)

patient_id               0
age                      0
gender                   0
admission_type           0
comorbidity_score        0
heart_rate_mean          0
heart_rate_std           0
heart_rate_max           0
heart_rate_min           0
systolic_bp_mean         0
systolic_bp_std          0
respiratory_rate_mean    0
spo2_mean                0
temperature_mean         0
glucose_mean             0
lactate_mean             0
urine_output_total       0
ventilation_required     0
vasopressor_used         0
length_of_stay_days      0
apache_score             0
sofa_score               0
sepsis_flag              0
mortality_label          0
dtype: int64

In [7]:
df['patient_id'].nunique()

15000

#### Checking Value Counts

In [8]:
cols = [
    'gender',
    'admission_type',
    'ventilation_required',
    'vasopressor_used',
    'sepsis_flag',
    'mortality_label'
]

for col in cols:
    print(f"\n{'='*50}")
    print(f"Value Counts for {col}")
    print(df[col].value_counts(dropna=False))

==================================================
Value Counts for gender
gender
Male      7523
Female    7477
Name: count, dtype: int64

==================================================
Value Counts for admission_type
admission_type
Elective     5068
Urgent       4967
Emergency    4965
Name: count, dtype: int64

==================================================
Value Counts for ventilation_required
ventilation_required
0    10467
1     4533
Name: count, dtype: int64

==================================================
Value Counts for vasopressor_used
vasopressor_used
0    11323
1     3677
Name: count, dtype: int64

==================================================
Value Counts for sepsis_flag
sepsis_flag
0    11971
1     3029
Name: count, dtype: int64

==================================================
Value Counts for mortality_label
mortality_label
0    11582
1     3418
Name: count, dtype: int64

#### Feature Engineering

##### Age Bucket

In [9]:
df['age_bucket'] = pd.cut(
    df['age'],
    bins=[17,29,39,49,59,69,90],
    labels=['18-29','30-39','40-49','50-59','60-69','70+']
)

##### LOS Bucket

In [10]:
df['los_bucket'] = pd.cut(
    df['length_of_stay_days'],
    bins=[0,3,7,14,30],
    labels=['1-3 Days','4-7 Days','8-14 Days','15+ Days']
)

##### APACHE Bucket

In [11]:
df['apache_bucket'] = pd.cut(
    df['apache_score'],
    bins=[0,10,20,30,40],
    labels=['0-10','11-20','21-30','31-40']
)

##### SOFA Bucket

In [12]:
df['sofa_bucket'] = pd.cut(
    df['sofa_score'],
    bins=[-1,5,10,15,20],
    labels=['0-5','6-10','11-15','16-20']
)

#### Analysis check

##### Comorbidity Bucket

In [13]:
pd.crosstab(
    df['age_bucket'],
    df['mortality_label'],
    normalize='index'
)*100

mortality_label          0          1
age_bucket
18-29            79.049154  20.950846
30-39            79.283260  20.716740
40-49            79.880180  20.119820
50-59            77.729469  22.270531
60-69            80.094340  19.905660
70+              72.248134  27.751866

##### Mortality by ventilation

In [14]:
pd.crosstab(
    df['ventilation_required'],
    df['mortality_label'],
    normalize='index'
)*100

mortality_label               0          1
ventilation_required
0                     80.357313  19.642687
1                     69.953673  30.046327

##### Mortality by Sepsis

In [15]:
pd.crosstab(
    df['sepsis_flag'],
    df['mortality_label'],
    normalize='index'
)*100

mortality_label          0          1
sepsis_flag
0                79.166319  20.833681
1                69.494883  30.505117

##### Mortality by Admission Type

In [16]:
pd.crosstab(
    df['admission_type'],
    df['mortality_label'],
    normalize='index'
)*100

mortality_label          0          1
admission_type
Elective         77.111287  22.888713
Emergency        76.938570  23.061430
Urgent           77.592108  22.407892

##### Mortality by APACHE Bucket

In [17]:
pd.crosstab(
    df['apache_bucket'],
    df['mortality_label'],
    normalize='index'
)*100

mortality_label          0          1
apache_bucket
0-10             79.360602  20.639398
11-20            80.398593  19.601407
21-30            76.993795  23.006205
31-40            73.173596  26.826404

In [18]:
df.to_csv(
    'icu_mortality_clean.csv',
    index=False
)