## Financial Performance and Profitability Analysis

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("datasets/fmcg_sales_dataset.csv")

In [3]:
pd.set_option('display.max_columns', None)
df.head()

,Order_ID,Order_Date,Year,Quarter,Month,Month_Name,Region,Country,City,Sales_Person,Customer_Type,Sales_Channel,Promotion_Type,Product_Category,Brand,Product_Name,SKU,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
0,FMCG-2025-000001,2025-09-26,2025,Q3,9,September,Oceania,Australia,Perth,Ethan Cole,B2C,Modern Trade,Seasonal Campaign,Personal Care,PureLiva,Shampoo Repair,PCR-PL-101,73,8.47,8.94,618.31,66.05,314.09,43.03,563.03,139.86,24.84
1,FMCG-2024-000002,2024-10-09,2024,Q4,10,October,Asia,India,Mumbai,Meera Nair,B2C,Online,Bundle Offer,Personal Care,BrightSmile,Toothpaste Mint,PCR-BS-301,99,2.89,9.86,286.11,35.26,123.79,23.89,257.90,74.96,29.07
2,FMCG-2024-000003,2024-07-06,2024,Q3,7,July,North America,USA,Los Angeles,Nina Booker,B2B,Distributor,Seasonal Campaign,Personal Care,FreshNest,Body Wash Citrus,PCR-FN-201,361,5.96,15.32,2151.56,171.46,1011.60,107.02,1821.94,531.86,29.19
3,FMCG-2024-000004,2024-05-25,2024,Q2,5,May,Europe,France,Paris,Oliver Kent,B2B,Wholesale,No Promo,Snacks,NutriBite,Protein Bar Peanut,SNK-NB-202,603,3.80,18.00,2291.40,118.39,1133.66,85.20,1878.95,541.70,28.83
4,FMCG-2023-000005,2023-08-10,2023,Q3,8,August,Europe,France,Lyon,Lucas Bennett,B2C,Modern Trade,Loyalty Cashback,Dairy & Breakfast,FarmJoy,Greek Yogurt Plain,DBF-FJ-202,113,3.18,12.46,359.34,34.82,157.70,23.02,314.57,99.03,31.48

#### Checking Basic specs

In [4]:
df.shape

(18240, 27)

In [5]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Year',
 'Quarter',
 'Month',
 'Month_Name',
 'Region',
 'Country',
 'City',
 'Sales_Person',
 'Customer_Type',
 'Sales_Channel',
 'Promotion_Type',
 'Product_Category',
 'Brand',
 'Product_Name',
 'SKU',
 'Units_Sold',
 'Unit_Price_USD',
 'Discount_Pct',
 'Gross_Sales_USD',
 'Marketing_Spend_USD',
 'COGS_USD',
 'Logistics_Cost_USD',
 'Net_Revenue_USD',
 'Profit_USD',
 'Profit_Margin_Pct']

In [6]:
df.dtypes

Order_ID                object
Order_Date              object
Year                     int64
Quarter                 object
Month                    int64
Month_Name              object
Region                  object
Country                 object
City                    object
Sales_Person            object
Customer_Type           object
Sales_Channel           object
Promotion_Type          object
Product_Category        object
Brand                   object
Product_Name            object
SKU                     object
Units_Sold               int64
Unit_Price_USD         float64
Discount_Pct           float64
Gross_Sales_USD        float64
Marketing_Spend_USD    float64
COGS_USD               float64
Logistics_Cost_USD     float64
Net_Revenue_USD        float64
Profit_USD             float64
Profit_Margin_Pct      float64
dtype: object

In [7]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Year                   0
Quarter                0
Month                  0
Month_Name             0
Region                 0
Country                0
City                   0
Sales_Person           0
Customer_Type          0
Sales_Channel          0
Promotion_Type         0
Product_Category       0
Brand                  0
Product_Name           0
SKU                    0
Units_Sold             0
Unit_Price_USD         0
Discount_Pct           0
Gross_Sales_USD        0
Marketing_Spend_USD    0
COGS_USD               0
Logistics_Cost_USD     0
Net_Revenue_USD        0
Profit_USD             0
Profit_Margin_Pct      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

##### Checking Profit and Profit pct columns

In [9]:
calculated_profit = (
    df['Net_Revenue_USD']
    - df['Marketing_Spend_USD']
    - df['COGS_USD']
    - df['Logistics_Cost_USD']
)

(df['Profit_USD'] - calculated_profit).abs().describe()

count    1.824000e+04
mean     4.522297e-14
std      7.166985e-14
min      0.000000e+00
25%      4.440892e-15
50%      2.131628e-14
75%      5.684342e-14
max      9.094947e-13
dtype: float64

In [10]:
calculated_margin = (
    df['Profit_USD'] / df['Net_Revenue_USD']
) * 100
(df['Profit_Margin_Pct'] - calculated_margin).abs().describe()

count    18240.000000
mean         0.002505
std          0.001440
min          0.000000
25%          0.001257
50%          0.002500
75%          0.003745
max          0.005000
dtype: float64

In [11]:
df[['Net_Revenue_USD', 'Profit_USD', 'Profit_Margin_Pct']].head(10)

   Net_Revenue_USD  Profit_USD  Profit_Margin_Pct
0           563.03      139.86              24.84
1           257.90       74.96              29.07
2          1821.94      531.86              29.19
3          1878.95      541.70              28.83
4           314.57       99.03              31.48
5           251.89       84.46              33.53
6           686.36      160.99              23.46
7           770.59      124.26              16.13
8            78.94       11.81              14.96
9          1098.96      374.26              34.06

In [12]:
calculated_margin = (
    df['Profit_USD'] / df['Net_Revenue_USD']
) * 100

pd.DataFrame({
    'Provided': df['Profit_Margin_Pct'],
    'Calculated': calculated_margin,
    'Difference': df['Profit_Margin_Pct'] - calculated_margin
}).head(10)

   Provided  Calculated  Difference
0     24.84   24.840595   -0.000595
1     29.07   29.065529    0.004471
2     29.19   29.191960   -0.001960
3     28.83   28.829932    0.000068
4     31.48   31.481069   -0.001069
5     33.53   33.530509   -0.000509
6     23.46   23.455621    0.004379
7     16.13   16.125307    0.004693
8     14.96   14.960730   -0.000730
9     34.06   34.055835    0.004165

In [13]:
df[['Units_Sold',
    'Unit_Price_USD',
    'Discount_Pct',
    'Gross_Sales_USD',
    'Marketing_Spend_USD',
    'COGS_USD',
    'Logistics_Cost_USD',
    'Net_Revenue_USD',
    'Profit_USD',
    'Profit_Margin_Pct']].describe()

,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
count,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000
mean,212.909759,4.467254,12.935771,936.431746,85.741888,471.024278,54.031789,792.210526,181.412572,19.870780
std,202.102318,1.949341,5.735972,1045.606955,87.551045,537.351019,51.266996,861.237271,239.526879,10.569275
min,5.000000,1.450000,0.000000,13.020000,1.810000,6.310000,1.080000,10.540000,-637.500000,-45.310000
25%,70.000000,3.020000,8.710000,274.532500,33.495000,140.510000,21.370000,245.217500,32.345000,13.720000
50%,139.000000,3.990000,12.690000,565.430000,61.385000,287.165000,38.985000,493.895000,91.890000,20.870000
75%,288.000000,5.440000,16.850000,1213.835000,107.605000,599.790000,69.240000,1027.362500,239.117500,27.260000
max,1366.000000,12.740000,28.000000,10634.120000,1767.710000,6473.330000,628.860000,8752.940000,2723.000000,44.490000

##### Checking Unique Values in specific columns

In [14]:
categorical_cols = [
    'Region',
    'Country',
    'City',
    'Sales_Person',
    'Customer_Type',
    'Sales_Channel',
    'Promotion_Type',
    'Product_Category',
    'Brand',
    'Product_Name',
    'SKU'
]

for col in categorical_cols:
    print(f"\n{col}:")
    print("Unique:", df[col].nunique())
    print(df[col].unique()[:20])

Region:
Unique: 5
['Oceania' 'Asia' 'North America' 'Europe' 'South America']

Country:
Unique: 17
['Australia' 'India' 'USA' 'France' 'Thailand' 'UK' 'Italy' 'Colombia'
 'Chile' 'Brazil' 'Spain' 'Mexico' 'Germany' 'Indonesia' 'Canada'
 'New Zealand' 'UAE']

City:
Unique: 48
['Perth' 'Mumbai' 'Los Angeles' 'Paris' 'Lyon' 'Bangkok' 'Hyderabad'
 'Manchester' 'Milan' 'Medellin' 'London' 'Valparaiso' 'Sao Paulo'
 'Madrid' 'Guadalajara' 'Hamburg' 'Delhi' 'Jakarta' 'Bengaluru'
 'Mexico City']

Sales_Person:
Unique: 36
['Ethan Cole' 'Meera Nair' 'Nina Booker' 'Oliver Kent' 'Lucas Bennett'
 'Nikhil Bhat' 'Farah Siddiqui' 'Marco Bellini' 'Elena Dupont'
 'Lucia Herrera' 'Mateo Silva' 'Hugo Martin' 'Rohan Iyer' 'Aarav Malhotra'
 'Javier Morales' 'Rizwan Khan' 'Diya Kapoor' 'Sharon Patel'
 'Andres Castillo' 'Sofia Mercer']

Customer_Type:
Unique: 2
['B2C' 'B2B']

Sales_Channel:
Unique: 4
['Modern Trade' 'Online' 'Distributor' 'Wholesale']

Promotion_Type:
Unique: 7
['Seasonal Campaign' 'Bundle Offer' 'No Promo' 'Loyalty Cashback'
 'Introductory Offer' 'Flash Discount' 'Festival Campaign']

Product_Category:
Unique: 5
['Personal Care' 'Snacks' 'Dairy & Breakfast' 'Household' 'Beverages']

Brand:
Unique: 17
['PureLiva' 'BrightSmile' 'FreshNest' 'NutriBite' 'FarmJoy' 'Softora'
 'FuelCore' 'SparkShield' 'CrunchMile' 'AquaGlow' 'PantryPeak'
 'RoastTrail' 'TrailNest' 'ZenLeaf' 'MorningCo' 'HomeNest' 'Biscora']

Product_Name:
Unique: 30
['Shampoo Repair' 'Toothpaste Mint' 'Body Wash Citrus'
 'Protein Bar Peanut' 'Greek Yogurt Plain' 'Paper Towels'
 'Energy Drink Classic' 'Glass Cleaner' 'Potato Chips BBQ'
 'Sparkling Water Lemon' 'Energy Drink Zero' 'Sparkling Water Berry'
 'Conditioner Smooth' 'Peanut Butter Creamy' 'Instant Coffee Gold'
 'Protein Bar Cocoa' 'Hand Soap Gentle' 'Yogurt Cup Strawberry'
 'Trail Mix Original' 'Green Tea Bags']

SKU:
Unique: 30
['PCR-PL-101' 'PCR-BS-301' 'PCR-FN-201' 'SNK-NB-202' 'DBF-FJ-202'
 'HHD-SF-302' 'BEV-FC-201' 'HHD-SS-202' 'SNK-CM-102' 'BEV-AG-101'
 'BEV-FC-202' 'BEV-AG-102' 'PCR-PL-102' 'DBF-PP-301' 'BEV-RT-301'
 'SNK-NB-201' 'PCR-FN-202' 'DBF-FJ-201' 'SNK-TN-301' 'BEV-ZL-401']

##### Feature Engineering

###### Revenue per unit

In [15]:
df['Revenue_per_Unit'] = df['Net_Revenue_USD'] / df['Units_Sold']

###### Total Cost

In [16]:
df['Total_Cost_USD'] = (df['COGS_USD'] + df['Marketing_Spend_USD'] + df['Logistics_Cost_USD'])

###### Marketing ROI

In [17]:
df['Marketing_ROI'] = (df['Profit_USD']/df['Marketing_Spend_USD'])

###### Discount Amount

In [18]:
df['Discount_Amount_USD'] = (df['Gross_Sales_USD']*df['Discount_Pct']/100)

###### Converting Order_Date data type

In [21]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

###### Year-Month

In [22]:
df['Year_Month'] = df['Order_Date'].dt.to_period('M').astype(str)

In [28]:
df['Order_Date'].dtype

dtype('<M8[ns]')

In [24]:
df[['Revenue_per_Unit',
    'Total_Cost_USD',
    'Marketing_ROI',
    'Discount_Amount_USD',
    'Year_Month']].head(10)

,Revenue_per_Unit,Total_Cost_USD,Marketing_ROI,Discount_Amount_USD,Year_Month
0,7.712740,423.17,2.117487,55.276914,2025-09
1,2.605051,182.94,2.125922,28.210446,2024-10
2,5.046925,1290.08,3.101948,329.618992,2024-07
3,3.116003,1337.25,4.575555,412.452000,2024-05
4,2.783805,215.54,2.844055,44.773764,2023-08
5,2.493960,167.43,2.864993,43.028828,2025-05
6,4.428129,525.37,2.141679,62.287680,2025-03
7,5.750672,646.33,0.946959,115.146200,2025-01
8,4.385556,67.13,0.894020,7.636356,2025-03
9,3.350488,724.70,5.837779,239.277312,2024-12

In [25]:
df.shape

(18240, 32)

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.dtypes

Order_ID                       object
Order_Date             datetime64[ns]
Year                            int64
Quarter                        object
Month                           int64
Month_Name                     object
Region                         object
Country                        object
City                           object
Sales_Person                   object
Customer_Type                  object
Sales_Channel                  object
Promotion_Type                 object
Product_Category               object
Brand                          object
Product_Name                   object
SKU                            object
Units_Sold                      int64
Unit_Price_USD                float64
Discount_Pct                  float64
Gross_Sales_USD               float64
Marketing_Spend_USD           float64
COGS_USD                      float64
Logistics_Cost_USD            float64
Net_Revenue_USD               float64
Profit_USD                    float64
Profit_Margin_Pct             float64
Revenue_per_Unit              float64
Total_Cost_USD                float64
Marketing_ROI                 float64
Discount_Amount_USD           float64
Year_Month                     object
dtype: object

In [29]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Year                   0
Quarter                0
Month                  0
Month_Name             0
Region                 0
Country                0
City                   0
Sales_Person           0
Customer_Type          0
Sales_Channel          0
Promotion_Type         0
Product_Category       0
Brand                  0
Product_Name           0
SKU                    0
Units_Sold             0
Unit_Price_USD         0
Discount_Pct           0
Gross_Sales_USD        0
Marketing_Spend_USD    0
COGS_USD               0
Logistics_Cost_USD     0
Net_Revenue_USD        0
Profit_USD             0
Profit_Margin_Pct      0
Revenue_per_Unit       0
Total_Cost_USD         0
Marketing_ROI          0
Discount_Amount_USD    0
Year_Month             0
dtype: int64

In [30]:
df[['Units_Sold', 'Unit_Price_USD', 'Gross_Sales_USD',
    'Marketing_Spend_USD', 'COGS_USD', 'Logistics_Cost_USD',
    'Net_Revenue_USD', 'Profit_USD', 'Profit_Margin_Pct']].describe()

,Units_Sold,Unit_Price_USD,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
count,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000
mean,212.909759,4.467254,936.431746,85.741888,471.024278,54.031789,792.210526,181.412572,19.870780
std,202.102318,1.949341,1045.606955,87.551045,537.351019,51.266996,861.237271,239.526879,10.569275
min,5.000000,1.450000,13.020000,1.810000,6.310000,1.080000,10.540000,-637.500000,-45.310000
25%,70.000000,3.020000,274.532500,33.495000,140.510000,21.370000,245.217500,32.345000,13.720000
50%,139.000000,3.990000,565.430000,61.385000,287.165000,38.985000,493.895000,91.890000,20.870000
75%,288.000000,5.440000,1213.835000,107.605000,599.790000,69.240000,1027.362500,239.117500,27.260000
max,1366.000000,12.740000,10634.120000,1767.710000,6473.330000,628.860000,8752.940000,2723.000000,44.490000

In [31]:
df[['Revenue_per_Unit',
    'Total_Cost_USD',
    'Marketing_ROI',
    'Discount_Amount_USD']].describe()

       Revenue_per_Unit  Total_Cost_USD  Marketing_ROI  Discount_Amount_USD
count      18240.000000    18240.000000   18240.000000         18240.000000
mean           3.891750      610.797954       2.150629           144.221196
std            1.727934      657.269944       1.949225           199.874417
min            1.108253        9.560000      -0.787053             0.000000
25%            2.616137      202.277500       0.871982            24.124823
50%            3.472256      394.605000       1.635429            67.770567
75%            4.773590      781.392500       2.825551           183.356325
max           12.211619     7669.580000      13.296935          2540.186650

In [32]:
df[['Revenue_per_Unit',
    'Total_Cost_USD',
    'Marketing_ROI',
    'Discount_Amount_USD']].lt(0).sum()

Revenue_per_Unit         0
Total_Cost_USD           0
Marketing_ROI          784
Discount_Amount_USD      0
dtype: int64

In [33]:
(df['Profit_USD'] < 0).sum()

np.int64(784)

#### Inspecting and Analysing Loss

In [34]:
loss_df = df[df['Profit_USD'] < 0]

loss_df[['Units_Sold',
         'Unit_Price_USD',
         'Discount_Pct',
         'Gross_Sales_USD',
         'Marketing_Spend_USD',
         'COGS_USD',
         'Logistics_Cost_USD',
         'Net_Revenue_USD',
         'Profit_USD',
         'Profit_Margin_Pct']].describe()

,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
count,784.000000,784.000000,784.000000,784.000000,784.000000,784.00000,784.000000,784.000000,784.000000,784.000000
mean,97.868622,4.742207,11.818482,459.008839,114.279298,269.43963,38.052653,396.647258,-25.124324,-7.161352
std,107.566840,2.483510,4.933050,607.896676,140.250429,363.83197,38.084726,500.369009,44.863451,7.257244
min,6.000000,1.660000,0.000000,13.370000,4.040000,6.85000,1.140000,11.480000,-637.500000,-45.310000
25%,44.000000,3.007500,8.325000,169.635000,37.325000,99.98500,15.680000,149.937500,-28.892500,-9.802500
50%,75.500000,3.555000,11.665000,294.180000,76.285000,168.76000,27.370000,261.105000,-11.450000,-4.680000
75%,108.250000,5.975000,14.795000,532.285000,141.202500,308.85000,48.212500,468.945000,-4.102500,-2.027500
max,1104.000000,11.730000,28.000000,7446.040000,1435.910000,4525.72000,398.880000,5848.860000,-0.010000,-0.010000

In [35]:
loss_df[['Product_Category',
         'Promotion_Type',
         'Sales_Channel',
         'Customer_Type']].describe(include='object')

       Product_Category     Promotion_Type Sales_Channel Customer_Type
count               784                784           784           784
unique                5                  7             4             2
top           Beverages  Seasonal Campaign        Online           B2C
freq                510                164           578           660

In [36]:
loss_df['Product_Name'].value_counts().head(10)

Product_Name
Sparkling Water Berry    165
Instant Coffee Gold      121
Sparkling Water Lemon    118
Green Tea Bags            57
Potato Chips Sea Salt     31
Energy Drink Classic      31
Chocolate Cookies         23
Protein Bar Cocoa         19
Protein Bar Peanut        18
Energy Drink Zero         18
Name: count, dtype: int64

In [37]:
loss_df['Promotion_Type'].value_counts()

Promotion_Type
Seasonal Campaign     164
Flash Discount        155
Festival Campaign     142
No Promo              124
Bundle Offer          109
Introductory Offer     60
Loyalty Cashback       30
Name: count, dtype: int64

In [38]:
loss_df['Sales_Channel'].value_counts()

Sales_Channel
Online          578
Modern Trade    167
Distributor      25
Wholesale        14
Name: count, dtype: int64

In [39]:
category_loss = df.groupby('Product_Category').agg(
    total_orders=('Order_ID', 'count'),
    loss_orders=('Profit_USD', lambda x: (x < 0).sum()),
    total_profit=('Profit_USD', 'sum')
).reset_index()

category_loss['loss_rate_pct'] = (
    category_loss['loss_orders'] /
    category_loss['total_orders'] * 100
)

category_loss.sort_values('loss_rate_pct', ascending=False)

    Product_Category  total_orders  loss_orders  total_profit  loss_rate_pct
0          Beverages          4356          510     524201.65      11.707989
4             Snacks          4283          125     555212.09       2.918515
2          Household          3237           55     832221.58       1.699104
1  Dairy & Breakfast          2925           45     620349.83       1.538462
3      Personal Care          3439           49     776980.16       1.424833

In [40]:
channel_loss = df.groupby('Sales_Channel').agg(
    total_orders=('Order_ID', 'count'),
    loss_orders=('Profit_USD', lambda x: (x < 0).sum()),
    total_profit=('Profit_USD', 'sum')
).reset_index()

channel_loss['loss_rate_pct'] = (
    channel_loss['loss_orders'] /
    channel_loss['total_orders'] * 100
)

channel_loss.sort_values('loss_rate_pct', ascending=False)

  Sales_Channel  total_orders  loss_orders  total_profit  loss_rate_pct
2        Online          5544          578     176025.87      10.425685
1  Modern Trade          6219          167     660266.21       2.685319
0   Distributor          3629           25    1123393.98       0.688895
3     Wholesale          2848           14    1349279.25       0.491573

In [41]:
customer_loss = df.groupby('Customer_Type').agg(
    total_orders=('Order_ID', 'count'),
    loss_orders=('Profit_USD', lambda x: (x < 0).sum()),
    total_profit=('Profit_USD', 'sum')
).reset_index()

customer_loss['loss_rate_pct'] = (
    customer_loss['loss_orders'] /
    customer_loss['total_orders'] * 100
)

customer_loss.sort_values('loss_rate_pct', ascending=False)

  Customer_Type  total_orders  loss_orders  total_profit  loss_rate_pct
1           B2C          9077          660     636569.93       7.271125
0           B2B          9163          124    2672395.38       1.353269

In [42]:
promotion_loss = df.groupby('Promotion_Type').agg(
    total_orders=('Order_ID', 'count'),
    loss_orders=('Profit_USD', lambda x: (x < 0).sum()),
    total_profit=('Profit_USD', 'sum')
).reset_index()

promotion_loss['loss_rate_pct'] = (
    promotion_loss['loss_orders'] /
    promotion_loss['total_orders'] * 100
)

promotion_loss.sort_values('loss_rate_pct', ascending=False)

       Promotion_Type  total_orders  loss_orders  total_profit  loss_rate_pct
1   Festival Campaign          1531          142     218696.37       9.274984
3  Introductory Offer           751           60     105226.15       7.989348
2      Flash Discount          2140          155     306545.88       7.242991
6   Seasonal Campaign          2895          164     477538.93       5.664940
0        Bundle Offer          2784          109     487231.45       3.915230
4    Loyalty Cashback          1398           30     281314.87       2.145923
5            No Promo          6741          124    1432411.66       1.839490

In [43]:
product_loss = df.groupby('Product_Name').agg(
    total_orders=('Order_ID', 'count'),
    loss_orders=('Profit_USD', lambda x: (x < 0).sum()),
    total_profit=('Profit_USD', 'sum')
).reset_index()

product_loss['loss_rate_pct'] = (
    product_loss['loss_orders'] /
    product_loss['total_orders'] * 100
)

product_loss.sort_values('loss_rate_pct', ascending=False).head(10)

,Product_Name,total_orders,loss_orders,total_profit,loss_rate_pct
22,Sparkling Water Berry,693,165,29851.81,23.809524
12,Instant Coffee Gold,653,121,114301.14,18.529862
23,Sparkling Water Lemon,680,118,38650.00,17.352941
10,Green Tea Bags,656,57,83331.85,8.689024
18,Potato Chips Sea Salt,697,31,51414.53,4.447633
5,Energy Drink Classic,823,31,120061.86,3.766707
2,Chocolate Cookies,754,23,92122.93,3.050398
3,Conditioner Smooth,541,15,150884.60,2.772643
19,Protein Bar Cocoa,720,19,113752.37,2.638889
17,Potato Chips BBQ,680,17,55263.16,2.500000

In [44]:
channel_loss = df.groupby('Sales_Channel').agg(
    total_orders=('Order_ID', 'count'),
    loss_orders=('Profit_USD', lambda x: (x < 0).sum()),
    total_profit=('Profit_USD', 'sum')
).reset_index()

channel_loss['loss_rate_pct'] = (
    channel_loss['loss_orders'] / channel_loss['total_orders'] * 100
)

channel_loss.sort_values('loss_rate_pct', ascending=False)

  Sales_Channel  total_orders  loss_orders  total_profit  loss_rate_pct
2        Online          5544          578     176025.87      10.425685
1  Modern Trade          6219          167     660266.21       2.685319
0   Distributor          3629           25    1123393.98       0.688895
3     Wholesale          2848           14    1349279.25       0.491573

##### Why online is losing  money?

In [45]:
channel_financial = df.groupby('Sales_Channel').agg(
    orders=('Order_ID', 'count'),
    avg_units=('Units_Sold', 'mean'),
    avg_discount=('Discount_Pct', 'mean'),
    avg_marketing_spend=('Marketing_Spend_USD', 'mean'),
    avg_cogs=('COGS_USD', 'mean'),
    avg_logistics=('Logistics_Cost_USD', 'mean'),
    avg_net_revenue=('Net_Revenue_USD', 'mean'),
    avg_profit=('Profit_USD', 'mean'),
    avg_margin=('Profit_Margin_Pct', 'mean')
).reset_index()

channel_financial.sort_values('avg_profit')

,Sales_Channel,orders,avg_units,avg_discount,avg_marketing_spend,avg_cogs,avg_logistics,avg_net_revenue,avg_profit,avg_margin
2,Online,5544,61.291486,8.859607,46.425875,150.106521,27.566506,255.849600,31.750698,12.777413
1,Modern Trade,6219,138.383985,12.550921,74.595978,318.346799,42.939862,542.051831,106.169193,19.907959
0,Distributor,3629,338.114081,15.791582,116.621904,722.107211,78.442993,1226.732312,309.560204,25.455580
3,Wholesale,2848,511.252809,18.071973,147.266046,1109.187665,98.665204,1828.882697,473.763782,26.481443

In [46]:
online_loss = df[
    (df['Sales_Channel'] == 'Online') &
    (df['Profit_USD'] < 0)
]

online_loss[['Product_Category',
             'Promotion_Type',
             'Product_Name']].value_counts().head(15)

Product_Category  Promotion_Type     Product_Name
Beverages         Seasonal Campaign  Sparkling Water Lemon    25
                                     Sparkling Water Berry    25
                  Flash Discount     Sparkling Water Berry    21
                  No Promo           Sparkling Water Berry    20
                  Bundle Offer       Instant Coffee Gold      18
                  Festival Campaign  Sparkling Water Lemon    16
                  No Promo           Instant Coffee Gold      15
                  Bundle Offer       Sparkling Water Berry    15
                  No Promo           Sparkling Water Lemon    15
                  Festival Campaign  Sparkling Water Berry    14
                                     Instant Coffee Gold      13
                  Flash Discount     Instant Coffee Gold      13
                  Seasonal Campaign  Instant Coffee Gold      13
                  Flash Discount     Sparkling Water Lemon    12
                  Bundle Offer       Sparkling Water Lemon    11
Name: count, dtype: int64

In [47]:
online_loss.groupby('Product_Category').agg(
    loss_orders=('Order_ID', 'count'),
    avg_profit=('Profit_USD', 'mean'),
    avg_discount=('Discount_Pct', 'mean'),
    avg_marketing_spend=('Marketing_Spend_USD', 'mean'),
    avg_logistics=('Logistics_Cost_USD', 'mean')
).sort_values('loss_orders', ascending=False)

,loss_orders,avg_profit,avg_discount,avg_marketing_spend,avg_logistics
Product_Category,,,,,
Beverages,368,-20.130082,10.402745,69.980734,33.634212
Snacks,91,-16.312198,9.874945,68.780769,18.221209
Personal Care,46,-25.178913,11.088696,121.822391,29.794783
Household,40,-29.213250,11.498250,135.830500,38.666000
Dairy & Breakfast,33,-16.510606,10.283636,111.207879,28.300606