## Financial Performance and Profitability Analysis

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("datasets/fmcg_sales_dataset.csv")

In [3]:
pd.set_option('display.max_columns', None)
df.head()

,Order_ID,Order_Date,Year,Quarter,Month,Month_Name,Region,Country,City,Sales_Person,Customer_Type,Sales_Channel,Promotion_Type,Product_Category,Brand,Product_Name,SKU,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
0,FMCG-2025-000001,2025-09-26,2025,Q3,9,September,Oceania,Australia,Perth,Ethan Cole,B2C,Modern Trade,Seasonal Campaign,Personal Care,PureLiva,Shampoo Repair,PCR-PL-101,73,8.47,8.94,618.31,66.05,314.09,43.03,563.03,139.86,24.84
1,FMCG-2024-000002,2024-10-09,2024,Q4,10,October,Asia,India,Mumbai,Meera Nair,B2C,Online,Bundle Offer,Personal Care,BrightSmile,Toothpaste Mint,PCR-BS-301,99,2.89,9.86,286.11,35.26,123.79,23.89,257.90,74.96,29.07
2,FMCG-2024-000003,2024-07-06,2024,Q3,7,July,North America,USA,Los Angeles,Nina Booker,B2B,Distributor,Seasonal Campaign,Personal Care,FreshNest,Body Wash Citrus,PCR-FN-201,361,5.96,15.32,2151.56,171.46,1011.60,107.02,1821.94,531.86,29.19
3,FMCG-2024-000004,2024-05-25,2024,Q2,5,May,Europe,France,Paris,Oliver Kent,B2B,Wholesale,No Promo,Snacks,NutriBite,Protein Bar Peanut,SNK-NB-202,603,3.80,18.00,2291.40,118.39,1133.66,85.20,1878.95,541.70,28.83
4,FMCG-2023-000005,2023-08-10,2023,Q3,8,August,Europe,France,Lyon,Lucas Bennett,B2C,Modern Trade,Loyalty Cashback,Dairy & Breakfast,FarmJoy,Greek Yogurt Plain,DBF-FJ-202,113,3.18,12.46,359.34,34.82,157.70,23.02,314.57,99.03,31.48

#### Checking Basic specs

In [4]:
df.shape

(18240, 27)

In [5]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Year',
 'Quarter',
 'Month',
 'Month_Name',
 'Region',
 'Country',
 'City',
 'Sales_Person',
 'Customer_Type',
 'Sales_Channel',
 'Promotion_Type',
 'Product_Category',
 'Brand',
 'Product_Name',
 'SKU',
 'Units_Sold',
 'Unit_Price_USD',
 'Discount_Pct',
 'Gross_Sales_USD',
 'Marketing_Spend_USD',
 'COGS_USD',
 'Logistics_Cost_USD',
 'Net_Revenue_USD',
 'Profit_USD',
 'Profit_Margin_Pct']

In [6]:
df.dtypes

Order_ID                object
Order_Date              object
Year                     int64
Quarter                 object
Month                    int64
Month_Name              object
Region                  object
Country                 object
City                    object
Sales_Person            object
Customer_Type           object
Sales_Channel           object
Promotion_Type          object
Product_Category        object
Brand                   object
Product_Name            object
SKU                     object
Units_Sold               int64
Unit_Price_USD         float64
Discount_Pct           float64
Gross_Sales_USD        float64
Marketing_Spend_USD    float64
COGS_USD               float64
Logistics_Cost_USD     float64
Net_Revenue_USD        float64
Profit_USD             float64
Profit_Margin_Pct      float64
dtype: object

In [7]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Year                   0
Quarter                0
Month                  0
Month_Name             0
Region                 0
Country                0
City                   0
Sales_Person           0
Customer_Type          0
Sales_Channel          0
Promotion_Type         0
Product_Category       0
Brand                  0
Product_Name           0
SKU                    0
Units_Sold             0
Unit_Price_USD         0
Discount_Pct           0
Gross_Sales_USD        0
Marketing_Spend_USD    0
COGS_USD               0
Logistics_Cost_USD     0
Net_Revenue_USD        0
Profit_USD             0
Profit_Margin_Pct      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

##### Checking Profit and Profit pct columns

In [9]:
calculated_profit = (
    df['Net_Revenue_USD']
    - df['Marketing_Spend_USD']
    - df['COGS_USD']
    - df['Logistics_Cost_USD']
)

(df['Profit_USD'] - calculated_profit).abs().describe()

count    1.824000e+04
mean     4.522297e-14
std      7.166985e-14
min      0.000000e+00
25%      4.440892e-15
50%      2.131628e-14
75%      5.684342e-14
max      9.094947e-13
dtype: float64

In [10]:
calculated_margin = (
    df['Profit_USD'] / df['Net_Revenue_USD']
) * 100
(df['Profit_Margin_Pct'] - calculated_margin).abs().describe()

count    18240.000000
mean         0.002505
std          0.001440
min          0.000000
25%          0.001257
50%          0.002500
75%          0.003745
max          0.005000
dtype: float64

In [11]:
df[['Net_Revenue_USD', 'Profit_USD', 'Profit_Margin_Pct']].head(10)

   Net_Revenue_USD  Profit_USD  Profit_Margin_Pct
0           563.03      139.86              24.84
1           257.90       74.96              29.07
2          1821.94      531.86              29.19
3          1878.95      541.70              28.83
4           314.57       99.03              31.48
5           251.89       84.46              33.53
6           686.36      160.99              23.46
7           770.59      124.26              16.13
8            78.94       11.81              14.96
9          1098.96      374.26              34.06

In [12]:
calculated_margin = (
    df['Profit_USD'] / df['Net_Revenue_USD']
) * 100

pd.DataFrame({
    'Provided': df['Profit_Margin_Pct'],
    'Calculated': calculated_margin,
    'Difference': df['Profit_Margin_Pct'] - calculated_margin
}).head(10)

   Provided  Calculated  Difference
0     24.84   24.840595   -0.000595
1     29.07   29.065529    0.004471
2     29.19   29.191960   -0.001960
3     28.83   28.829932    0.000068
4     31.48   31.481069   -0.001069
5     33.53   33.530509   -0.000509
6     23.46   23.455621    0.004379
7     16.13   16.125307    0.004693
8     14.96   14.960730   -0.000730
9     34.06   34.055835    0.004165

In [13]:
df[['Units_Sold',
    'Unit_Price_USD',
    'Discount_Pct',
    'Gross_Sales_USD',
    'Marketing_Spend_USD',
    'COGS_USD',
    'Logistics_Cost_USD',
    'Net_Revenue_USD',
    'Profit_USD',
    'Profit_Margin_Pct']].describe()

,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
count,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000
mean,212.909759,4.467254,12.935771,936.431746,85.741888,471.024278,54.031789,792.210526,181.412572,19.870780
std,202.102318,1.949341,5.735972,1045.606955,87.551045,537.351019,51.266996,861.237271,239.526879,10.569275
min,5.000000,1.450000,0.000000,13.020000,1.810000,6.310000,1.080000,10.540000,-637.500000,-45.310000
25%,70.000000,3.020000,8.710000,274.532500,33.495000,140.510000,21.370000,245.217500,32.345000,13.720000
50%,139.000000,3.990000,12.690000,565.430000,61.385000,287.165000,38.985000,493.895000,91.890000,20.870000
75%,288.000000,5.440000,16.850000,1213.835000,107.605000,599.790000,69.240000,1027.362500,239.117500,27.260000
max,1366.000000,12.740000,28.000000,10634.120000,1767.710000,6473.330000,628.860000,8752.940000,2723.000000,44.490000

##### Checking Unique Values in specific columns

In [14]:
categorical_cols = [
    'Region',
    'Country',
    'City',
    'Sales_Person',
    'Customer_Type',
    'Sales_Channel',
    'Promotion_Type',
    'Product_Category',
    'Brand',
    'Product_Name',
    'SKU'
]

for col in categorical_cols:
    print(f"\n{col}:")
    print("Unique:", df[col].nunique())
    print(df[col].unique()[:20])

Region:
Unique: 5
['Oceania' 'Asia' 'North America' 'Europe' 'South America']

Country:
Unique: 17
['Australia' 'India' 'USA' 'France' 'Thailand' 'UK' 'Italy' 'Colombia'
 'Chile' 'Brazil' 'Spain' 'Mexico' 'Germany' 'Indonesia' 'Canada'
 'New Zealand' 'UAE']

City:
Unique: 48
['Perth' 'Mumbai' 'Los Angeles' 'Paris' 'Lyon' 'Bangkok' 'Hyderabad'
 'Manchester' 'Milan' 'Medellin' 'London' 'Valparaiso' 'Sao Paulo'
 'Madrid' 'Guadalajara' 'Hamburg' 'Delhi' 'Jakarta' 'Bengaluru'
 'Mexico City']

Sales_Person:
Unique: 36
['Ethan Cole' 'Meera Nair' 'Nina Booker' 'Oliver Kent' 'Lucas Bennett'
 'Nikhil Bhat' 'Farah Siddiqui' 'Marco Bellini' 'Elena Dupont'
 'Lucia Herrera' 'Mateo Silva' 'Hugo Martin' 'Rohan Iyer' 'Aarav Malhotra'
 'Javier Morales' 'Rizwan Khan' 'Diya Kapoor' 'Sharon Patel'
 'Andres Castillo' 'Sofia Mercer']

Customer_Type:
Unique: 2
['B2C' 'B2B']

Sales_Channel:
Unique: 4
['Modern Trade' 'Online' 'Distributor' 'Wholesale']

Promotion_Type:
Unique: 7
['Seasonal Campaign' 'Bundle Offer' 'No Promo' 'Loyalty Cashback'
 'Introductory Offer' 'Flash Discount' 'Festival Campaign']

Product_Category:
Unique: 5
['Personal Care' 'Snacks' 'Dairy & Breakfast' 'Household' 'Beverages']

Brand:
Unique: 17
['PureLiva' 'BrightSmile' 'FreshNest' 'NutriBite' 'FarmJoy' 'Softora'
 'FuelCore' 'SparkShield' 'CrunchMile' 'AquaGlow' 'PantryPeak'
 'RoastTrail' 'TrailNest' 'ZenLeaf' 'MorningCo' 'HomeNest' 'Biscora']

Product_Name:
Unique: 30
['Shampoo Repair' 'Toothpaste Mint' 'Body Wash Citrus'
 'Protein Bar Peanut' 'Greek Yogurt Plain' 'Paper Towels'
 'Energy Drink Classic' 'Glass Cleaner' 'Potato Chips BBQ'
 'Sparkling Water Lemon' 'Energy Drink Zero' 'Sparkling Water Berry'
 'Conditioner Smooth' 'Peanut Butter Creamy' 'Instant Coffee Gold'
 'Protein Bar Cocoa' 'Hand Soap Gentle' 'Yogurt Cup Strawberry'
 'Trail Mix Original' 'Green Tea Bags']

SKU:
Unique: 30
['PCR-PL-101' 'PCR-BS-301' 'PCR-FN-201' 'SNK-NB-202' 'DBF-FJ-202'
 'HHD-SF-302' 'BEV-FC-201' 'HHD-SS-202' 'SNK-CM-102' 'BEV-AG-101'
 'BEV-FC-202' 'BEV-AG-102' 'PCR-PL-102' 'DBF-PP-301' 'BEV-RT-301'
 'SNK-NB-201' 'PCR-FN-202' 'DBF-FJ-201' 'SNK-TN-301' 'BEV-ZL-401']