### Financial Performance and Profitability Analysis

In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_excel("datasets/india_retail_data.xlsx")
df.head()

,Order Priority,Discount offered,Unit Price,Freight Expenses,Freight Mode,Segment,Product Type,Product Sub-Category,Product Container,State,City,Region,Country,Order Date,Ship Date,Profit,QtyOrdered,Sales
0,High,0.06,40.98,2.99,Regular Air,Personel Usage,Processed Meat,Bacon,Small Box,Madhya Pradesh,Rewa,West,India,2010-01-02,2010-01-04,-19.0992,3,124.81
1,High,0.05,155.06,7.07,Regular Air,Hotels / Hospitals,Processed Meat,Fresh Water Eel,Small Box,Meghalaya,Shillong,East,India,2010-01-02,2010-01-09,845.6640,8,1225.60
2,High,0.09,9.11,2.15,Express Air,Personel Usage,Processed Meat,Smoked Salmon,Wrap Bag,Maharashtra,Parbhani,West,India,2010-01-02,2010-01-04,20.2996,4,34.41
3,High,0.08,15.04,1.97,Regular Air,Personel Usage,Processed Meat,Smoked Salmon,Wrap Bag,Maharashtra,Parbhani,West,India,2010-01-02,2010-01-02,108.5163,11,157.27
4,High,0.03,4.26,1.20,Regular Air,Restaurant Chain,Processed Meat,Foie Gras,Wrap Bag,Uttar Pradesh,Ghaziabad,North,India,2010-01-03,2010-01-04,9.8200,29,122.23

In [3]:
df.shape

(2534, 18)

In [5]:
df.isnull().sum()

Order Priority          0
Discount offered        0
Unit Price              0
Freight Expenses        0
Freight Mode            0
Segment                 0
Product Type            0
Product Sub-Category    0
Product Container       0
State                   0
City                    0
Region                  0
Country                 0
Order Date              0
Ship Date               0
Profit                  0
QtyOrdered              0
Sales                   0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Order Priority,2534,5,High,1624,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount offered,2534.0,NaN,NaN,NaN,0.04965,0.0001,0.02,0.05,0.08,0.1,0.032171
Unit Price,2534.0,NaN,NaN,NaN,100.151405,0.99,6.48,20.89,89.95,6783.02,357.023226
Freight Expenses,2534.0,NaN,NaN,NaN,12.222261,0.49,2.99,6.05,12.98,110.2,16.092475
Freight Mode,2534,3,Regular Air,1892,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Segment,2534,4,Hotels / Hospitals,869,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Type,2534,3,Processed Meat,1407,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Sub-Category,2534,17,Smoked Salmon,399,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Container,2534,7,Small Box,1296,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,2534,22,Uttar Pradesh,473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,2534,339,Rewa,196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,2534,4,North,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,2534,1,India,2534,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Date,2534,NaN,NaN,NaN,2012-03-14 20:56:26.898184704,2010-01-02 00:00:00,2011-03-12 00:00:00,2012-05-12 00:00:00,2013-03-26 00:00:00,2013-12-30 00:00:00,NaN
Ship Date,2534,NaN,NaN,NaN,2012-03-16 21:46:27.371744512,2010-01-02 00:00:00,2011-03-13 00:00:00,2012-05-14 00:00:00,2013-03-28 00:00:00,2013-12-30 00:00:00,NaN
Profit,2534.0,NaN,NaN,NaN,112.576198,-14369.12358,-86.377263,1.23125,121.263,16332.414,1055.205939
QtyOrdered,2534.0,NaN,NaN,NaN,14.238358,1.0,5.0,10.0,17.0,170.0,16.014995
Sales,2534.0,NaN,NaN,NaN,992.623717,1.62,62.5925,191.16,793.8475,100119.16,3147.339693